### PR TITLE
Cities

### PR DESCRIPTION
**Pull request by T1m1**

### CODE REVIEW

**Comment by timoweiss** [comment]
what is this PR about? "Cities" is a crappy title.

**Comment by T1m1** [comment]
like my only commit message .. "delete route /data/cities/trips and use /data/cities instead."

**Comment by timoweiss** [comment]
so why don't you just use this?

**Comment by T1m1** [comment]
Yesterday, we discussed it. We don't need a route to get all cities anymore. Only a route to get all cities with trips.

**Comment by timoweiss** [comment]
I mean, why can't you just provide a speaking title and a short description for the PR? No one would ever look at a PR like this in the wild ;)

**Comment by T1m1** [comment]
Nobody in the whole wide world will ever watch one of our PR  :laughing:

**Pull request merged**
